components/webfield/SeniorAreaChairConsole.js, tests/profilePage.ts
this pr should fix a typo in sac console notes filtering logic (by venue id)
=> Fix/ SAC console desk-rejected note filtering

pages/search.js
Show most recently updated notes first in results.
Related to https://github.com/openreview/openreview/issues/149
=> Fix/ Search page: sort results by date modified

components/FeedbackModal.js, components/IconButton.js, pages/signup.js, pages/user/moderation.js, styles/components.scss, styles/global.scss, tests/feedback.ts
this pr should:
1. update feedback topic of adding institution to  "Please add to your list of publishing institutions"
2. to  show an X button so we can delete the whole text in order to select another reason
3. add the geolocation info when we add domains using the moderation UI
3 requires https://github.com/openreview/openreview-api/pull/331 so that state/province is allowed in api validation
=> Fix/Some changes to feedback form and institution list UI

components/webfield/ReviewerConsole.js
this pr should fix paper with no review in reviewer console
=> Fix/Reviewer console - paper with no review

tests/profilePage.ts
Change sort param in test that is no longer supported by API
=> Fix/ Update test for new API validation

components/invitation/InvitationEditor.js, components/invitation/InvitationReply.js, pages/invitation/info.js
this pr should support message invitations in invitation editor
=> Feature/Invitation editor: let view and edit message invitations

client/webfield-v2.js, components/MessagesTable.js
this pr should update "Message Log" link in messages page to v2 
this pr should also update post message endpoint in webfield which is used by journal consoles (renderTable method)
=> Fix/Messages UI: message log is pointing to API 1

components/webfield/ProgramChairWithSeniorReviewerConsole.js
this pr should add emailing senior reviewers and emailing reviewers + senior reviewers function in ProgramChairWithSeniorReviewerConsole paper status tab as requested by CoLLAs 2024 organizers
=> Feature/PC Console with Senior Reviewers - add email senior reviewers options

client/view-v2.js
This is needed for this PR: https://github.com/openreview/openreview-py/pull/1998
I am creating an invitation used only to delete/restore submissions. This means the invitation does not have a content
=> Fix/ Note editor: check if invitation has note.content

components/profile/EducationHistorySection.js, components/profile/ProfileEditor.js, tests/profilePage.ts
this pr should fix the two issues described in #1860
=> Fix/Profile edit validation: mark required fields correctly

components/webfield/ProgramChairConsole/ReviewerStatus.js
this pr should fix the js error when reviewer has no profile
=> Fix/ PC console: load registration notes for reviewers

components/NoteEditor.js, components/form/ToggleButtonGroup.js, components/forum/Forum.js, styles/components/forum.scss, tests/profilePage.ts
Also adds tooltips to the readers filter and removes the login prompt when unauthenticated users load the page. Users will only be prompted to login when they click an invitation button.
Fixes #1892 
Fixes #1875
=> Fix/ Forum page: add pagination for forums with many replies 

components/invitation/InvitationReply.js
then the reply field has no value, it just shows [] or {}
so the code editor should always be shown
=> Fix/Invitation Editor - code editor is removed when value is cleared

components/forum/FilterTabs.js, components/forum/Forum.js
- Fix error with posting non-chat notes
- Update note signatures after loading new signature groups
=> Fix/ Forum page: improve browser notifications

.vscode/next.code-snippets, components/forum/ChatReply.js, components/forum/Forum.js
- Change notification text
- Scroll to note when browser notification is clicked
- Load tag, but currently do not show them
=> Fix/ Forum chat: show tags in chat replies

pages/profile/edit.js, tests/profilePage.ts
this is the ui change for
https://github.com/openreview/openreview-api/pull/428
api will return error message with links to profile and docs
so this pr should allow markdown error message when profile is saved
=> Fix/Profile edit - allow error message with links

components/forum/ForumReply.js
Fix `excludedInvitations` condition
=> Fix/ Forum page: don't hide invitation buttons when excludedInvitations not set

components/webfield/ProgramChairConsole/PaperStatusMenuBar.js, unitTests/PaperStatusMenuBar.test.js
this pr should add support for function strings so that the query search can search for arbitrary field
=> Fix/PC Console - Allow functions for search query

components/webfield/NoteMetaReviewStatus.js, components/webfield/ProgramChairConsole/AreaChairStatusMenuBar.js, components/webfield/ProgramChairConsole/PaperStatusMenuBar.js, components/webfield/SeniorAreaChairConsole/AreaChairStatus.js
related to #1947 
to add some default value to components used by SAC console
=> Fix/SAC console - Add some default values for configs

pages/user/moderation.js
New users can now confirm emails before profile is activated.
this pr should update the rejection message accordingly
=> Fix/ Moderation page - rejection message

components/PaginatedList.js
this pr should fix the issue that the formulas are not rendered in group homepage (submission list)
submission list is the only place that may show formula
=> Fix/ Submission list - render Mathjax formula

pages/user/moderation.js
UI changes for https://github.com/openreview/openreview-api-v1/pull/2990
this pr should change the moderation page to load/post only v2 config note
also renamed configNoteV2 to configNote
=> Fix/Moderation - load only v2 config note

components/forum/Forum.js
this pr should fix #2003 
cause is explained in issue
=> Fix/ Display odate in submission forum UI

components/EditorComponents/DatePickerWidget.js, components/invitation/InvitationGeneral.js, lib/utils.js, unitTests/utils.test.js
this pr should fix the issue that the page shows undefined error when user click archive upload button
invitation general info edit may have similar issue
the issue is caused by logic error in getDefaultTimeZone fn and it may cause the offset string to be wrong so that no matching timezone could be found
this pr should:
1. fix the wrong hour caused by Math.floor on negative value
2. fix the +/- sign of minutes when offset minutes is negative
3. add optional chaining so it does not throw error when there's no matching timezone 
4. add some tests
=> Fix/ Archive upload undefined error

components/profile/BasicProfileView.js, components/profile/EducationHistorySection.js, components/profile/ProfileEditor.js, pages/profile/index.js, styles/pages/profile.scss, tests/profilePage.ts, tests/registerPage.ts, tests/utils/api-helper.js
this pr should fix #2014 
the profile page is 100px wider to make room for department
=> Feature/ Profile improvements

unitTests/AreaChairConsole.test.js
this pr is related to #2023
this pr includes updates in AC console test for the iThenticate changes made in #2023
=> Fix/ iThenticate AC Console test

components/profile/ImportedPublicationsSection.js, components/profile/ProfileEditor.js, tests/profilePage.ts
At first I removed the Imported Publications completely if the user didn't have any, but I thought that could be unclear.
Instead I replaced the text in this case to `No publications listing you as an author were found in DBLP and other sources.`
=> Profile editor for user without publications

components/webfield/NoteMetaReviewStatus.js, components/webfield/NoteReviewStatus.js
Check for reviewers before adding the Show/Hide links.
Before Reviewers are assigned:<img width="1180" alt="PC_Console_no_reviewers" src="https://github.com/user-attachments/assets/c4818c5a-c5b7-44af-9452-ca90b631df45">
And with Reviewers:
=> Only show the ""Show/Hide reviewers" if there are assigned reviewers.

components/NoteContent.js, components/forum/ForumNote.js, lib/banner-links.js, lib/forum-utils.js, pages/forum.js, pages/revisions/index.js
this pr should fix the forum page when all edits of a forum note are deleted.
requires https://github.com/openreview/openreview-api/pull/513
=> Fix/ Forum - forum page with all edits being deleted

components/webfield/ProgramChairConsole.js, components/webfield/ProgramChairConsole/RejectedWithdrawnPapers.js, components/webfield/ProgramChairConsole/RejectedWithdrawnPapersMenuBar.js, components/webfield/SeniorAreaChairConsole.js, unitTests/SeniorAreaChairConsole.test.js
this pr should add in SAC console a new tab to show withdrawn and desk rejected papers assigned to the SAC
the tab is the same as the one in pc console but shows only the assigned papers
=> Feature/ SAC console - withdrawn/rejected papers tab

components/webfield/MessageReviewersModal.js, components/webfield/ProgramChairConsole.js, components/webfield/ProgramChairConsole/PaperStatusMenuBar.js, unitTests/MessageReviewersModal.test.js
this pr should add an option in pc console paper status tab to email authors of selected papers
=> Feature/ PC Console - allow sending emails to authors

components/DatetimePicker.js, components/EditorComponents/DatePickerWidget.js, lib/dayjsGenerator.js, package-lock.json, package.json, styles/components/datetime-picker.scss
this pr should add support of 
- maximum
- minimum
- range
to date picker widget
the dates outside of maximum, minimum and range are disabled
=> Feature/ DatePicker widget - support maximum and minimum

components/EditorComponents/ToggleButtonWidget.js, styles/components/ToggleButtonWidget.module.scss, unitTests/ToggleButtonWidget.test.js
this pr should implement a toggle button widget
as toggle button does not have a null/empty state
it will set value to false once it's displayed (for example the submission invitation with no default value)
=> Feature/ Toggle button widget

components/forum/ForumReply.js, styles/components/forum.scss
this pr should replace pencil icon in forum reply with by and reduce excess padding
purpose of pencil icon is unknown
=> Fix/ Replace pen icon with by

lib/edge-utils.js, pages/assignments/index.js
edge browser required preferredEmailInvitationId query param to show copy email link in profile entitiy
this pr should read domain object for preferredEmailInvitationId
so that the param can be added to edge browser url if it exists
=> Fix/ Assignments - read preferredEmailInvitationId from domain

app/FeedbackLink.js, app/Footer.js, app/signup/Signup.js, components/FeedbackModal.js, styles/components/footer.scss
feedback modal is now placed inside feedback link so it requires some update to be shown properly for mobile
=> Fix/ Show feedback modal properly for mobile

components/webfield/VenueHomepage.js
related to #2247 
support chained path so that details.writable value can be found
=> Fix/ Award committee authored paper filtering

pages/messages.js
related to #2216 where the loading status is broken when there's no message
this pr should fix the loading status
=> Fix/ Messages - loading status when no message is found

pages/user/moderation.js
the log link in email deletion tab is wrong using note id instead of log id
this pr should fix this issue
=> Fix/ Moderation - Log link in email deletion tab

components/webfield/ProgramChairConsole/AreaChairStatus.js, components/webfield/ProgramChairConsole/ReviewerStatus.js
currently the SAC title is showing the title of AC which is wrong
this pr should SAC title
=> Fix/ PC console AC status - show SAC title correctly

tests/_setup.ts
similar change to github.com/openreview/openreview-py/pull/2549
otherwise revision process would fail and post submission date process will get stuck
=> Fix/ Test setup - make sure the order of cdate <= duedate <= expdate

components/group/GroupRelatedInvitations.js, components/invitation/InvitationEditor.js, components/invitation/InvitationGeneral.js, components/webfield/SubmissionButton.js, pages/invitation/edit.js, styles/pages/group.scss, styles/pages/invitation.scss
this pr should allow ddate to be added/removed in invitation editor
=> Fix/ Invitation Editor - Add ddate

components/webfield/ProgramChairConsole/ReviewerStatus.js
this pr should show rating in reviewer status tab when the rating value is 0
=> Fix/ PC Console Reviewer Status - Show 0 rating

client/view.js
this pr should fix https://github.com/openreview/openreview-py/pull/2576#discussion_r2067429555
so https://github.com/openreview/openreview-py/pull/2576 can be deployed
=> Fix/ V1 checkbox input wrong value when string has double quote

components/profile/ProfilePreviewModal.js, lib/utils.js, pages/user/moderation.js, styles/components.scss
this pr should 
- add rejection option to request vouching
- add a reject button to reject for missing institutional email
=> Fix/ Moderation - add vouching message

lib/utils.js
this pr should fix the checking of mandatory fields
when the invitation specify a const, mandatory fields does not apply
=> Fix/ Console tasks - handle const field

app/AppInit.js, app/assignments/V2Assignments.js, components/webfield/AreaChairConsoleMenuBar.js, tests/forumPage.ts
this pr should fix the following issues:
1. bibtex modal link is not shown when clicking bibtex/show bibtex(v1) link in forum page
bibtex modal is missing
3. "View details" link in assignments page for assignment notes with no solution or error does not show popover of error message
popover is not initialized
=> Fix/ Bibtex is not showing and Assignments error details not showing

package-lock.json, package.json
Bump version to 1.14.8 in package.json and package-lock.json
=> Bump version to 1.14.8 in package.json and package-lock.json

components/webfield/BidConsole.js, unitTests/BidConsole.test.js
this pr should change getAll calls in bid console to get call using stream=true to improve api query performance
it can be changed because they don't need details
=> Fix/ BidConsole - update API calls to use streaming for notes and edges

app/(Home)/page.js, app/version/route.js, components/VersionChecker.js, store.js, unitTests/VersionChecker.test.js, versionSlice.js
this pr should add version check when user navigate to home page
and show a banner to remind user to refresh page if browser version is outdated
=> Fix/ Add version check

app/user/moderation/UserModerationTab.js
this pr should replace reject button with accept button for rejected profiles
=> Fix/ User Moderation - allow accepting rejected profiles

components/webfield/BasicHeader.js, components/webfield/ReviewerConsole.js, package-lock.json, package.json
this pr should add doc for variables used in reviewer console config
this pr should also fix the issue with custom load comparison and fix missing config logic for recruitmentInvitationId
it used to be for v2 only and is moved to the list of missing configs as v1 logic is removed.
=> Fix/ Reviewer Console - add doc for config

app/group/Group.module.scss, app/invitation/Invitation.module.scss, components/webfield/ProgramChairConsole.js
this pr should change id (so that url hash) of overview tab from venue-configuration to overview
so that it's consistent
=> Fix/ PC Console - change id of overview tab

app/profile/edit/LimitedStateAlert.js, components/profile/EducationHistorySection.js, lib/utils.js
this pr may fix the difficulty of adding custom positions by handling blur event of the position dropdown
this pr should also do some code cleanup
=> Fix/ Profile edit - position input
