openreview/openreview-web

client/view-v2.js
lib/api-client.js

this pr should fix the following issues:
1. getInvitationById  and getNoteById are passing v2 param to v1 query (https://github.com/openreview/openreview-web/pull/862/files#r930117068)
2. edit.note.content.{field}.readers checking is wrong. 
currently it checks for reader.const which was changed during development of api.
correct check is reader.param, if there's no reader.param it's const array value

Fix/ Some issues in api client and construct edit

---

pages/assignments/index.js

Some venues like Journals will run matchings for a subset of papers, we should allow them to deploy multiple configuration. Add this setting to the configuration invitation content.
Setting is set here: https://github.com/openreview/openreview-py/pull/1989

Fix/ Assignment page: show deploy link based on invitation configuration or note status

---

pages/user/moderation.js

this change is missed from #1741
to read profile_id.value as the link to profile in email deletion tab

Fix/API 2 Email deletion link to profile

---

lib/webfield-utils.js

some invitations may not have the complete role name and are filtered out in tasks by filterAssignedInvitations
for example a review revision invitation which should be shown in reviewer console tasks
is filtered out because both id (review_revision) and invitee(review anon id) do not have role name "Reviewers"
this pr should update the filtering to include singular role name too

Fix/Console tasks - filter singular role name

---

components/webfield/AuthorConsole.js

Emilia mentioned in the daily meeting that author console should show only the confidence number
this pr should update the author console to show only the confidence number

Fix/ Author console - show confidence mark only

---

components/webfield/AreaChairConsole.js
components/webfield/AreaChairConsoleMenuBar.js
components/webfield/AuthorConsole.js
components/webfield/NoteReviewStatus.js
components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/PaperStatusMenuBar.js
components/webfield/ProgramChairConsole/ReviewerStatus.js
components/webfield/ReviewerConsole.js
components/webfield/SeniorAreaChairConsole.js

this pr should support fallback rating names in consoles, for example the following review rating setting
```
"review_rating": {
"value": [
{
"overall_rating": [
"final_rating",
"preliminary_rating"
]
},
"overall_recommendation",
]
}
``` 
should display 2 ratings:
- Overall Rating
it's value will be final_rating field, when final_rating field is not available, it will take the next available value defined in the array, in this example it will take "preliminary_rating"
- Overall Recommendation

Feature/ Consoles - Support fallback rating names

---

components/NoteEditor.js

currently when secondary ac post a note when secondary ac group is not in note readers, the secondary ac won't be added as note readers
this pr should fix this issue by adding secondary ac group or ac group in note readers
this pr assumes that secondary ac group is member of ac group

Fix/ Add Secondary AC or AC in missing readers

---

components/webfield/AreaChairConsole.js

this pr should add support of secondary ac assignments in ac console triplet ac assignments tab
example config:
>secondaryAreaChairName: "Secondary_Area_Chairs"
menu bar is not included in this pr due to time. it requires separating tab data from assigned papers tab because the "tableRowsAll" name in setData is fixed

Feature/ AC Console - support secondary AC in triplet AC assignments tab

---

components/webfield/NoteMetaReviewStatus.js
components/webfield/ProgramChairConsole.js
components/webfield/SeniorAreaChairConsole.js

Show secondary ACs in the AC Status column for the SAC console:
- Add new property to enable secondary area chairs
- Read the secondary area chairs groups
- Assign them to secondary area chairs data and show them in the UI
PC console changes are pending.

Consoles: show secondary ACs

---

.github/workflows/build.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

Update github actions to use latest versions with Node.js v20 runners.
Required because of https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Fix/ Update GitHub actions

---

pages/user/moderation.js

currently moderation page is reading the moderate status and terms timestamp from v1 config note and is also updating only the v1 config note when moderate value is updated.
this pr should change it to read the value from v2 config note instead
changing moderate status will update v2 config note because new profiles are now created calling v2 api
changing terms timestamp will still update both config notes

Fix/ Moderation - update v2 config note

---

components/webfield/AreaChairConsole.js
components/webfield/AuthorConsole.js
components/webfield/ConsoleTaskList.js
components/webfield/ReviewerConsole.js
lib/utils.js
unitTests/ConsoleTaskList.test.js

- fix typo in property
- enable `filterAssignedInvitation` in the AC console tasks
- support "Meta_Review" in the pretty invitation id
the AC console should render the following task: 
thecvf.com/CVPR/2024/Conference/Submission4/Meta_Review1/-/Revision
as "Submission4 Meta Review1 Revision"

ConsoleTasks: fix typo and filter by assigned task in the AC console

---

components/webfield/AreaChairConsole.js
components/webfield/AreaChairConsoleMenuBar.js
components/webfield/NoteMetaReviewStatus.js
components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/PaperStatus.js
components/webfield/ProgramChairConsole/PaperStatusMenuBar.js
components/webfield/SeniorAreaChairConsole.js
components/webfield/SeniorAreaChairConsole/PaperStatus.js

this pr should support a new config 
>additionalMetaReviewFields
in PC/SAC/AC console 
example config
>additionalMetaReviewFields:["final_recommendation"]
this pr should show the additionalMetaReviewFields values of meta review in paper status tab if available (apart from recommendation value) .
the additionalMetaReviewFields should also be query filterable

Feature/ PC/SAC/AC console - support display and search or additional meta review fields

---

tests/utils/api-helper.js

There's a new validation in API to disallow empty history when creating a profile
this pr should change the test setup so that test can pass

Fix/ Empty history error in test setup

---

pages/_app.js

when impersonating a pre-created dblp profile with no email, the page will show an error reading from undefined value (impersonation still works)
this pr should fix the error

Fix/ Error impersonating user with no linked email

---

components/ProfileListWithBidWidget.js
components/webfield/NoteMetaReviewStatus.js
components/webfield/NoteReviewStatus.js
components/webfield/ProgramChairConsole/AreaChairStatus.js
components/webfield/ProgramChairConsole/ReviewerStatus.js
components/webfield/ProgramChairConsole/SeniorAreaChairStatus.js
components/webfield/ReviewerConsole.js
components/webfield/SeniorAreaChairConsole/AreaChairStatus.js
lib/webfield-utils.js
tests/_setup.ts

this pr should fix the following 2 issues:
1. add a link to profile for reviewers/ACs/Secondary ACs/SACs
2. correct the link to secondary AC group page instead of the non-existing profile page in reviewer console
currently the group member hierarchy is :
- per paper ACs
- AC anon group
- secondary ACs
- secondary AC anon group
so "secondary ACs" group is rendered in reviewer console
CVPR 24 reviewer console can be used as example

Feature/Consoles - Add profile link

---

components/webfield/ProgramChairConsole/Overview.js
components/webfield/ProgramChairWithSeniorReviewerConsole.js

this pr should add a component
>ProgramChairWithSeniorReviewerConsole
as temp fix for venue with senior reviewers until multiple reviewer groups is supported
(ProgramChairWithSeniorReviewerConsole.js can be deleted after the conference with senior reviewer is over)
this component has the following extra parameters compared to pc console (CoLLAs 2024 as an example):
```javascript
...
seniorReviewersId :'lifelong-ml.cc/CoLLAs/2024/Conference/Senior_Reviewers',
seniorOfficialReviewName: 'Senior_Official_Review',
seniorReviewerName: 'Senior_Reviewers',
anonSeniorReviewerName: 'Senior_Reviewer_',
...
```
function is the same as pc console with added info for senior reviewers in overview tab,paper status tab and senior reviewer status tab
decided that messaging senior reviewers from paper …

Fix/Temp fix of PC console for venue with senior reviewers

---

components/webfield/BidConsole.js

this pr should remove domain param from notes search calls in bidding console

Fix/ Bidding Console: remove the call to domain when searching several notes by id

---

components/group/GroupEditor.js
components/group/GroupRelatedInvitations.js
pages/group/info.js

this pr should make group editor related invitations section to use a regex prefix that can load more invitations such as 
>thecvf.com/CVPR/2024/Conference/Submission4/Meta_Review1/-/Final_Revision 
where "-" does not follow group id directly (user is at thecvf.com/CVPR/2024/Conference/Submission4 group)

Fix/Group editor: load all related invitations

---

components/DblpImportModal.js
lib/profiles.js

currently a use can use a dblp url as long as any of the user's names appear in any of the listed papers
this pr should only allow import if the user's name match with the names specified in dblp xml
this is part of the preparation for auto profile merge

Fix/ Don't allow user to import from DBLP with coauthor's persistent URL

---

components/webfield/AreaChairConsole.js

currently the referrer url always use #assigned-papers tab
this pr should make the links to go back to the specific tab
for example user click the read review link in secondary reviewers tab and click the go back to AC console link in banner of forum page, it should display secondary reviewers tab instead of assigned papers tab

Feature/ AC Console - change referrer url to specific tab

---

components/group/GroupEditor.js
components/group/GroupRelatedInvitations.js
components/group/GroupSignedNotes.js
pages/group/info.js

currently group editor use getCombined to load signed notes and related invitations.
this pr should change it to only load from api which match with the group version by checking group.domain

Fix/Group Editor: remove calls to API 1 when the group is created in API 2

---

pages/profile/activate.js
tests/utils/api-helper.js

api validation of /activate/{token}: has been updated to allow only content field
this pr should fix activate page and test setup to pass only content field

Fix/ Profile activation - update data for new api validation

---

components/webfield/EditorWidget.js
unitTests/EditorWidget.test.js

There is a new `profile` type validation that we are using for the `authorids` field. When using type `profile/profile[]`, we should render the ProfileSearchWidget.

Fix/ Note editor: render ProfileSearchWidget for profile/profile[]

---

components/forum/ForumReply.js

this pr should hide reply button in forum replies when
the invitation note reader has everyone but the parent note is not publicly visible
the readers won't match so that the note editor simply fails to load when the invitation button is clicked
an example is public comment invitation on decision reply or review

Fix/ Forum reply - don't show reply invitation button when readers won't match

---

components/FeedbackModal.js

this pr contains similar change to #1865 to update the subject of feedback emails so that the emails are not grouped to one thread

Fix/Add venue/submission id to feedback email subject

---

components/DblpPublicationTable.js
lib/profiles.js
tests/profilePage.ts

currently dblp import of papers from venues hosted on openreview is not allowed if the venue in dblp and in openreview is the same.
this pr should change it to only check for previously imported dblp papers instead of all papers associated with authors (those submitted to a venue) so that the dblp paper can be imported
this pr should also add referrer param to papers imported from dblp so that the banner can navigate back to user's profile edit page which currently navigates to non-existing group

Fix/DBLP import - Allow importing from venues that is hosted by openreview

---

components/webfield/EthicsChairConsole/EthicsChairMenuBar.js
components/webfield/EthicsChairConsole/EthicsChairPaperStatus.js

currently ethics chair console expect the per paper ethics reviewers group to contain the tilde ids of ethics reviewers
while the new logic has changed to member of per paper ethics reviewers group to the anonymous id group of each assigned ethics reviewer
this pr should update the mapping logic accordingly
the changes should be compatible with the case where tilde ids are added as member of ethics reviewers group directly (for example NeurIPS 2023)
this pr should also fix query searching ethics reviewers by name or email (right now this is not working properly)

Fix/Ethics Chair console - anonymous group data loading logic update

---

components/browser/EdgeBrowser.js

in edge browser when an assigned reviewer is removed from the reviewers pool without deleting the edge
the reviewer is added to the column as a dummy profile  with only the tilde id
currently its search text is also the tilde id
this caused the reviewer to appear in search result when part of the name is searched but not when the full name or tilde id is search.
for example the reviewer's tilde id is ~Abc_Edf1
the search will work when user search for 
- abc
- edf
- abc_edf
but not when search term is
- abc edf - because of the missing underscore
- ~Abc_Edf1 - because the regex has a word boundary \b and ~ will break it
this pr should add the pretty id of the tilde id to the search text so that when user search for "abc edf" the reviewer can be found.
this is only done for reviewers with …

Fix/ Edge browser - search text of dummy profiles

---

components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/AreaChairStatus.js
components/webfield/ProgramChairConsole/AreaChairStatusMenuBar.js
components/webfield/ProgramChairConsole/ReviewerStatus.js
components/webfield/ProgramChairConsole/ReviewerStatusMenuBar.js

Adds user defined and labeled emailing functions in the PC Console webfield config
Adds registration notes to the reviewer/AC rows to be accessible by custom functions
Example:
```
reviewerFilterFuncs: [
{
label: 'Reviewer Two', filterFunc: `
return row.reviewerProfileId === '~Reviewer_ARRTwo1'
`
},
]
```
ARR Use Cases from Legacy Webfields:
1) Messaging users without a maximum load reply, this is usually for recruitment that occurs 2-3 weeks before the submission deadline:
```
var loadNote = row.profile.allNames?.flatMap(name => conferenceStatusData.maximumLoadNotes[name])
.find(note => note.invitation.includes('/Area_Chairs/'));
var regNote = row.profile.allNames?.flatMap(name => conferenceStatusData.registrationNotes[name])
.find(note => note.invitation.includes('/Area_Chairs/')); …
```

Feature/ PC console: load registration notes for reviewers, ACs, and SACs

---

lib/utils.js
tests/tasksPage.ts
tests/tasksPageV1.ts
unitTests/ConsoleTaskList.test.js

It seems that check to mark as task as complete is the existence of the `repliedEdits` but some of these edits could be deleting the reply note. 
If a review is deleted, the task still appears a complete and it should be back to pending.
This PR checks the invitation has repliedEdits and the last edit doesn't content a note.ddate assuming the edits are sorted chronologically. @carlosmondra please confirm this is the case.
I created a new test case for API 2 tasks.

Fix/ Tasks page: mark task as incomplete if the reply is deleted

---

components/DblpImportModal.js
components/DblpPublicationTable.js

when a lot of papers (>1000) are selected for import
the browser will report error for insufficient resource
api will report error for max reply reached
cloud function to abstract extraction may throw service unavailable error (reason is unknown)
so this pr should allow user to select up to 500 papers for import to avoid error so that user don't keep retry importing which  may cause the process function queue to be blocked

Fix/ DBLP import - allow up to 500 papers to be imported each time

---

lib/utils.js
pages/user/moderation.js
styles/components.scss

currently accept profile action button is only available in the moderate only queue and not available in the all profiles queue
so when there are many profiles pending moderation it's tedious for the moderator to find a profile and activate it.
this pr should allow moderator to search a pending moderation profile from all profiles and accept it.
delete button is hidden for needs moderation profiles to make space for accept button
this pr should also sort the profiles pending moderation by modification date so that those old profiles which are claimed can be seen
this pr should also color the modification date of the profiles which has passed 2 weeks

Feature/ User moderation - allow moderator to search and accept a profile

---

components/ExpertiseSelector.js

when there's an error in the updated api.post (for example the note does not exist), the error is not handled as expected by the catch inside useeffect
this pr should move the call out so that post error can be handled properly

Fix/ Expertise selection: handle API error

---

components/browser/Column.js

currently when the custom quota is 0, the quotaNotReached value will be wrong
and it will cause the entity to appear in column even if the filter quota reached checkbox is checked
this pr should fix this issue

Fix/Edge browser - fix entity with 0 quota

---

components/browser/Column.js
components/webfield/ProgramChairConsole/AreaChairStatus.js
components/webfield/ProgramChairConsole/ReviewerStatus.js
lib/webfield-utils.js

this pr should:
1. add bid invitation as edit param in edge browser url for editing bids
2. remove weight from traverseEdges which was added to sort edges
3. not to add nonreaders when traverse (bid) invitation does not have it so that api validation does not fail

Fix/Edge browser - Bid/Recommendation edge browser url

---

components/browser/EdgeBrowser.js

a logic to show default value of custom max papers is added in
#941
this pr should skip that logic when user is redirected to edge browser from histogram in assignment statistics page
because when the data is from local storage the custom max papers edges are not loaded so it shows default value for all profile entitites

Fix/ Edge browser: don't show default value of ignore head browse invitation

---

lib/profiles.js

currently the first edit of DBLP import has formatted title (used for comparison) as title and it was overwritten when the edit of xml transformation/abstract extraction is posted.
this pr should change it to post the original title from the first edit

Fix/DBLP Import: send the publication title with their original case

---

pages/user/moderation.js

currently venues tab of moderation page show undeployed venues created in the past week on top of the list
it seems that a week is too short so this pr should change it to show all venues that are not deployed

Fix/ User moderation: show all venues that have not been deployed

---

components/webfield/ConsoleTaskList.js
components/webfield/ProgramChairConsole.js
components/webfield/SeniorAreaChairConsole.js
lib/webfield-utils.js
unitTests/ConsoleTaskList.test.js

this pr should fix the following 2 issues caused by overlapping role names:
1. in PC and SAC console - if reviewer name and ac name overlap, for example reviewer name is Program_Committee and ac name is Senior_Program_Committee, SAC console and PC console won't get the correct ac assigned to papers if the members of AC group is anonymous AC group instead of tiled ids
it's caused by the anon ac groups being treated as anon reviewer group and the anon ac group is used as ac instead of the tilde id inside the anon ac group (becomes the logic of non anon id)
2. in AC console tasks - if a user is both AC and SAC and role names of AC and SAC overlap, the SAC tasks won't be filtered out in AC console tasks

Fix/ SAC/PC Console - issues caused by overlapping role names

---

components/webfield/BasicHeader.js
components/webfield/ReviewerConsole.js

this pr is to append #1909 by moving the singularAreachairName logic after areaChairName check so that it does not break for venues with no AC
it should also parameterize submission name in reviewer console header when there's custom load (only used by reviewer console)

Fix/Reviewer Console - undefined error when there's no AC

---

tests/profilePage.ts

this pr should fix profile auto merge test due to api behavior change
previously a user (emailA) can request for merge with another profile (emailB) without saving emailB to profile
but now it requires the user to first save emailB to profile otherwise /mergelink call will fail with invalid token
so this pr changed to save the profile to add userF.email to userA's profile

Fix/ Error in profile auto merge test

---

tests/profilePage.ts

this pr should revert the fix added in #1953
as the issue is fixed in api (to allow user to merge with email which is not in profile at time of merge)

Fix/ Test - remove temp fix added for profile auto merge

---

components/EditorComponents/CheckboxWidget.js
unitTests/CheckboxWidget.test.js

the checkbox options display value is changed from 
>description
to
>label
in #1715, but the change is missed for items used for non note readers field which is causing the label to show empty
this pr should fix this issue

Fix/ Note Editor - show items checkbox label correctly

---

components/forum/Forum.js

this pr should fix the issue that submit review (or something else) link does not open the note editor in forum page when there's no reply.
when there's no orderedReplies, deayedScroll( which calls to open NoteEditor ) is skipped so note editor will not open.
related to #1498

Fix/ Forum page - note editor not shown when forum has no reply yet

---

components/webfield/MessageReviewersModal.js

Fix/PC Console - remove areachair name from single reviewer reminder modal

---

components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/AreaChairStatus.js
components/webfield/ProgramChairConsole/ReviewerStatus.js

This pr should change the pc console to load registration notes once when user open reviewer status tab/ac status tab
this pr should also show registration notes for reviewers and acs with no assignment

Fix/PC Console - Load Registration Notes

---

components/forum/Forum.js

when url has invitationId, the page should open note editor automatically.
this process is completed by finding the reply button which corresponds to the invitation and simulate clicking it.
it may fail when the function runs before the buttons complete rendering (so the button can't be found)
this pr may fix this issue by increasing delay for scrolling to selected note

Fix/ Forum page - note editor not open when query param has invitationId 

---

components/webfield/MessageReviewersModal.js
unitTests/MessageReviewersModal.test.js

currently the message reviewers modal is grouping the messages by preferredEmail to show a count of messages that will be sent to the user
when the emails are masked, the display will be wrong because emails from the same domain are grouped together (email sending is still correct )
this pr should change the grouping from email to id
this pr should also add some tests

Fix/Message Reviewers modal - fix grouping from email to id

---

components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/AreaChairStatusMenuBar.js
components/webfield/ProgramChairConsole/SeniorAreaChairStatus.js
components/webfield/ProgramChairConsole/SeniorAreaChairStatusMenuBar.js

pc console assumes that only ACs are assigned to SAC
so when papers are assigned to SAC directly (loaded by edge), it only shows some note id in SAC status tab.
this pr should add the following new configs to PC console
- **sacDirectPaperAssignment** - when set to true will show tab content and menu bar similar to ac status tab
- **sacStatuspropertiesAllowed** - overwrite the query search properties of sac status tab (has no effect if sacDirectPaperAssignment is false)
- **messageSeniorAreaChairsInvitationId** - the invitation id for sending messages to sac
- **sacEmailFuncs** - custom message options (array of object with fields label and filterFunc)
when the value is true, SAC console shows paper related data similar to what AC status tab is showing.

Fix/ PC Console - Show Correct Info when SAC is assigned to papers directly

---

components/NoteContent.js
unitTests/NoteContent.test.js

changes introduced in chat caused the mathajx typeset to be executed before the replies are actually rendered.
this can cause the formula in forum replies not to be rendered depends on how long it takes for mathjax to execute.
this pr should call mathjax in note content so that it's guaranteed to be rendered.

Fix/ Forum - Formula in forum reply may not get rendered

---

components/NoteContent.js
unitTests/NoteContent.test.js

a fix of formula rendering is added in #2002 to move mathjax call to note content
and it looks like it may cause some venue page to stuck
 
this pr should temporarily revert the fix made in #2002 till better fix is implemented

Fix/ Revert changes made in 2002

---

components/browser/ProfileEntity.js

currently when the browse invitation has head:ignore and has default weight/label, the default weight/label will be displayed as browse edge.
this applies even if the reviewer has been removed from the reviewers group (but still have assignment)
and it's difficult for AE to tell whether these entities should be assigned papers.
this pr should update the logic not to add head:ignore browse edges if profile is not in reviewers group

Fix/ Edge browser - Not to add ignore head browser edges for dummy profiles

---

components/webfield/ProgramChairConsole.js

an error will be thrown in
anonymousId: getIndentifierFromGroup(anonymizedGroup, anonReviewerName)
when anonymizedGroup is undefined
this happens when the paperX/reviewers/submitted is added as a member of paperY/reviewers group
fix is similar to #1617

Fix/PC console - error when paperX/reviewers/submitted group is added to paperY/reviewers group

---

components/browser/ProfileEntity.js

this pr should show email or copy email link (when preferredEmailInvitaitonId exists) below title in profile entity

Fix/ Edge browser - show email/copy email below title/institution

---

pages/index.js

this pr should :
1. continue showing other venue lists in homepage when some groups call fail/timeout
2. load only id of user consoles because only id is used

Fix/ Avoid API is unavailable in the home page

---

components/BasicModal.js
components/webfield/MessageReviewersModal.js
unitTests/MessageReviewersModal.test.js

currently the reviewer reminder api calls can exhaust browser resources when pc select many papers.
this pr should group every 1000 selected papers and chain the calls so that it doesn't fail
this pr should also change the send button to spinner button as it can take a while to send those messages

Fix/ Message Reviewers - batch every 1000 selected notes

---

components/group/GroupMembers.js
pages/user/moderation.js

this pr contains changes related to https://github.com/openreview/openreview-api/pull/495
when user edit member of old group with no invitations an error will be thrown by api for missing invitations
call in api helper is not removed so that tests still pass

Feature/ Remove calls to add and remove members endpoints

---

components/webfield/BidConsole.js
unitTests/BidConsole.test.js

currently the subject area dropdown search for a fixed field "subject_areas" using /notes/search route
bidding console can now specify a config 
> subjectAreasName
which is the note content field name which is used to compare with user selected subject area
when **subjectAreasName** is specified, the other config 
> subjectAreas
should be an array of objects with 2 fields: value and description
value is used to match note content field value and description is displayed in the subject areas field dropdown
the notes filtering method is also changed because not all note content fields are indexed so the filtering logic is moved inside the bidding console after getting all notes

Feature/ Bidding console - allow config to specify subject area field

---

components/webfield/AuthorConsole.js

this pr should update the profile loading logic using emails in author console
to avoid the case that multiple emails of one user are used in different papers and some papers will show the user is not active

Fix/ Author Console - change profiles call to load for each paper

---

components/assignments/HistogramStat.js
lib/assignment-stats-utils.js
pages/assignments/stats.js
styles/pages/assignment-stats.scss

this pr should update title/axis names in assignment stats page
currently it's reading config note's assignment_invitation content field to get invitation.edge.head.inGroup for the head name
when inGroup does not exist (for example role to paper matching) then it defaults to "papers"

Fix/ Assignment stats: If the assignment is to another group, change "Papers" to group name

---

components/forum/ForumReply.js
components/webfield/AreaChairConsole.js
components/webfield/SeniorAreaChairConsole.js
lib/banner-links.js
lib/forum-utils.js
pages/revisions/index.js
unitTests/AreaChairConsole.test.js

this pr should allow note reply to be displayed as [empty] when there's no visible content to the user
the note has no visible content to the user because the note invitation has readers for all content fields and the user is not included.
with changes in https://github.com/openreview/openreview-api/pull/503
the user can post the note but the posted note is not visible to the user
the user can still see contents in revisions page and activities page
the user won't be able to delete the invisible note because content is not available
the user can edit the note but there's no existing value so it's like posting a new note

Fix/ Forum reply - display note with no visible content

---

components/webfield/AreaChairConsoleMenuBar.js
components/webfield/ProgramChairConsole/PaperStatusMenuBar.js

currently average rating/confidence is of type string to keep the two-digit formatting.
when rating/confidence is between 0-9 this is fine but when rating/confidence goes over 10 it will cause some rows to be wrongly sorted.
for example when sorted by average rating, row with average rating = 11.00 will be placed between rows with rating = 1.00 and rows with rating = 2.00
this pr should fix this issue by converting the avg value to number (if convertible) before sorting.

Fix/ PC/SAC/AC console - convert avg rating/confidence to number

---

client/templates.js
client/templates/noteAreaChairs.hbs
client/templates/noteReviewers.hbs
client/webfield-v2.js
components/browser/ProfileEntity.js
components/webfield/NoteMetaReviewStatus.js
components/webfield/NoteReviewStatus.js
components/webfield/ProgramChairConsole/AreaChairStatus.js
components/webfield/ProgramChairConsole/ReviewerStatus.js
components/webfield/ProgramChairConsole/SeniorAreaChairStatus.js
components/webfield/SeniorAreaChairConsole/AreaChairStatus.js

this pr should fix the following issues:
1. message/error prompt causing the page to scroll to top in consoles
2. message/error prompt causing the page to scroll to top in journal (templates)
3. when user has no id the template still shows copy email (for example action editor is "No Action Editor")

Fix/ Console Email Copy - not to scroll to top

---

components/browser/Column.js

with changes in https://github.com/openreview/openreview-web/pull/1480
it's possible that checking the filter checkbox shows more entities which contradicts with user's intuition that checking the checkbox should show less items because the label says "Only show ..."
this pr should remove "only"

Fix/Edge browser- update checkbox wording

---

components/webfield/AreaChairConsole.js
components/webfield/AreaChairConsoleMenuBar.js
components/webfield/BaseMenuBar.js
components/webfield/ProgramChairConsole/PaperStatus.js
components/webfield/ProgramChairConsole/PaperStatusMenuBar.js
components/webfield/ProgramChairConsole/ReviewerStatusMenuBar.js
components/webfield/SeniorAreaChairConsole/PaperStatus.js
unitTests/BaseMenuBar.test.js

this pr should fix AC/SAC/PC console to clear selected note ids when user 
- perform a new (basic or query) search
- clear search term/query

Fix/PC Console - selected ids should be cleared when user perform new search

---

pages/login.js
tests/issue.ts

some users overlook the "Email" label and think they can use tild id or name to login
currently the login button is only disabled
this pr should add a tooltip when the email that user entered is invalid

Fix/ Login page - add tooltip when email is invalid

---

components/webfield/BidConsole.js
unitTests/BidConsole.test.js

this pr should add a config 
>enableSearch
which has default value true in bidding console to hide the search input (when set to false)
the use case is that the user should only see papers with a score edge

Fix/ Bidding Console - add enableSearch config to enable/disable search input

---

pages/tasks.js

this pr is a temporary fix for:
AE recommendation task of TMLR is for author to recommend 3 AEs for each paper submitted
when the author recommend 3 AEs, the tasks is displayed as completed in author console but still pending in tasks page
the issue is caused by the edge being posted using the non paper specific AE recommendation invitation while the invitations loaded in tasks page (and author console tasks tab) are paper specific. the consequence is that the repliedEdges can't be loaded correctly in invitation details and the task status is pending
TMLR author console is working because a custom logic being added because it's not using component webfield.
this pr should serve as a temporary fix of the discrepancy between author console and tasks page
this pr assumes:
- ae recommendation …

Fix/ Tasks - TEMP fix for completion status of AE recommendation task

---

components/webfield/AreaChairConsole.js

fix messaging in AC Console when AC can't see anon reviewer group

Fix/ AC console - fix messaging missing anon group when AC can't see anon reviewer group

---

components/webfield/ProgramChairConsole/PaperStatusMenuBar.js
components/webfield/SeniorAreaChairConsole/PaperStatus.js

pass default value only for sac console
so that venues with no sac role won't have the sac search key

Fix/ PC console Paper Status: Don't show SAC name as a property in the query search modal if there are no SACs

---

components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/AreaChairStatusMenuBar.js

this pr should add a config in PC console
> areaChairStatusPropertiesAllowed
which is the query search config overwrite for AC status tab
currently AC status tab reads the config "propertiesAllowed" which is for paper status tab but the data structure of paper status tab and ac status tab are different so it probably won't work.
the behavior of overwriting the default config is not changed because it's consistent with SAC status tab (direct paper assignment)

Fix/ PC Console - separate propertiesAllowed config for AC status tab

---

components/profile/ProfileEditor.js
pages/legal/terms.js
pages/login.js
tests/issue.ts
tests/registerPage.ts

currently only the privacy page last updated date is changed.
this pr should make the last updated date in 
- login page
- terms and conditions page
- signup page
to be consistent with privacy page
this pr should also add a test to make sure the date in these pages are always consistent

Fix/ Terms updated date

---

components/browser/ProfileEntity.js

when a browse invitation is ignore head invitation and it has a default value,
the default value was added to profile entity if the entity does not have such an edge.
currently these ignore head invitation default values edges are added to the end
this pr should sort the browse edges based on browse invitation so that they will be in the same sequence as in entities which has all the edges

Fix/ Random order in Reviewer properties

---

.github/workflows/build.yml

ubuntu-latest image used by github actions now has python 3.12.3 which is not compatible with openreview-py
so need to add a step to install an older version 3.10

Fix/ Fix github action error caused by python version

---

pages/_app.js
pages/messages.js
pages/notifications.js

ui changes required for https://github.com/openreview/openreview-api/pull/647
notification page/notification nav bar is changed to read count from messages length
message page has been changed to:
1. use after instead of limit/offset so page in query param is removed because passing limit/offset will cause api to return count which would timeout
2. as api returns up to 1000 results so each time user click "last page" it loads up to 40 pages as the page does not know the number of messages so it could only dynamically update the pagination as data loads

Fix/ Update count from /messages

---

lib/api-client.js

api requires the following conditions to return count:
-  query have both limit and offset
or
- query have count:true
in getAll function the count is required to determine whether to make subsequent api calls after offset 1000 so add count:true

Fix/ get count in getAll

---

components/webfield/EthicsChairConsole.js

ethicsReviewName is a required field to show meaningful info in ethics chair console
some ethics chairs would like to see the console before the ethics review stage start
so this pr should make ethicsReviewName optional so that ethics chair console loads(although empty)

Fix/ Ethics Chair Console - remove ethicsReviewName from required fields

---

components/profile/BasicProfileView.js
components/profile/ProfilePreviewModal.js
lib/utils.js
pages/user/moderation.js
styles/components.scss

this pr should implement an improvement @melisabok raised during meeting
to enable moderator to check and act on multiple profiles without leaving the profile preview modal
so that moderator does not need to click around

Fix/ Moderation - Allow moderating multiple profiles in preview modal

---

components/webfield/NoteMetaReviewStatus.js

Currently, if a meta review note doesn't contain a recommendation field the console will still show the field with an empty string next to it. This PR fixes it so that the field is only shown if the note contains the field. Ex:
Old:
New:

Consoles: Show Meta Review recommendation field only if the field exists in the note

---

components/webfield/AreaChairConsole.js
components/webfield/NoteReviewStatus.js
components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/PaperStatus.js
components/webfield/SeniorAreaChairConsole.js
components/webfield/SeniorAreaChairConsole/PaperStatus.js
styles/pages/group.scss
unitTests/SeniorAreaChairConsole.test.js

this pr should add in PC and SAC console paper status tab a new column (when displayReplyInvitations is specified) to show latest reply of the invitation and content fields specified.
sample config
```javascript
displayReplyInvitations: [
{
id: "acmmm.org/ACMMM/2024/Conference/Submission{number}/-/Official_Review",
fields: ["summary", "limitations"],
},
{
id: "acmmm.org/ACMMM/2024/Conference/Submission{number}/-/Public_Comment",
fields: ["strengths", "suitability"],
},
]
```

Fix/ PC/SAC Console - Add latest reply column in paper status tab

---

components/browser/Column.js

filter param in edge browser is in the form of 
browseInvitationId = value
where browse edges are added to row data as row.filterProperties.browseInvitationId
however when browseInvitationId contains dot (for example thecvf.com/...), the dot will be interpreted as a level of field in row and the filtering logic will compare the value of row[filterProperties][thecvf][com/...] and fail
this pr should replace all dot in filtering invitation to underscore

Fix/ Edge browser - replace dot in filter query

---

components/NoteEditorReaders.js
unitTests/NoteEditorReaders.test.js

this pr should add support of inGroup type in reply readers
members of the specified inGroup group will be added to options

Fix/ Anon group readers when reviewer is unassigned

---

lib/utils.js
pages/invitation/edit.js

invitation editor loads writableWith of the invitation (meta invitation)
which caused slowness of the page
this pr should remove loading writableWith and always use meta invitation

Fix/ Invitation editor - avoid loading writablewith

---

lib/utils.js
unitTests/utils.test.js

this pr should update the parse number util function to handle colon typo in invitation

Fix/ Parse whole string when there's no colon

---

pages/_app.js

this pr should force link in all markdown content to open in a new tab

Fix/ Markdown - force link to open in a new tab

---

components/NoteEditor.js
components/NoteEditorReaders.js
unitTests/NoteEditor.test.js

when user is not reader of the group defined by inGroup, getting inGroup member would fail preventing note editor from loading/ submitting
this pr should handle failure getting inGroup group members by returning empty array (like getting group by regex/prefix but didn't have any match)

Fix/ Handle get inGroup member failure

---

components/WebfieldContainer.js
styles/global.scss

bootstrap adding auto margin causing the margin to be too large in mobile view
this pr should overwrite margin in mobile view
this pr should also remove out-dated code to scroll page

Fix/ Mobile view wrong margin

---

.github/workflows/build.yml

This pull request includes a small update to the GitHub Actions workflow to refine the conditions under which the build job runs.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L157-R157): Updated the `if` condition for the `build` job to exclude cases where the event is a `repository_dispatch` with the action `openreview-api-updated`.

Chore: Avoid deploying to the dev site when API PRs are merged

---

lib/api-client.js
lib/clientAuth.js
middleware.js

this pr should send
url: page url or the api call url that failed before the /refreshtoken call
source: middleware or api client or client authentication
user: from refresh token (only for middleware)
in header of the call to /refreshtoken

Fix/ refreshtoken logging

---

components/forum/Forum.js
hooks/useUser.js

i think the issue with refresh token is chat making calls to check updates
this pr contains a temp fix to check for cookie token change so that the check updates call use new token instead of keep using expired token
currently the chat is the only place where polling (useInterval hook) is used
so the correct fix is to use web socket instead

Fix/ Temp fix of refresh token issue

---

components/ClientForumDate.js
components/Note.js
components/profile/ProfilePublications.js

Some notes in profile publications page may be rendered to different dates in server and client
and cause hydration error
this pr should render the publication dates in profile page only in the browser

Fix/ Profile page - publication published/modified date discrepancy in client rendering

---

app/assignments/V2Assignments.js

related to changes in https://github.com/openreview/openreview-api/pull/781
this pr should add missing count param which is required for assignments page to return count of assignment notes
Webfield2.api.getSubmissions should also be changed when webfield pass includeCount
but i think it's not used anymore so didn't change it

Fix/ Add missing count param

---

components/webfield/ProgramChairConsole/SeniorAreaChairStatus.js

This issue was reported by ARR and it is related to assigned papers that are not active anymore.
If the edge.head is pointing to a non active submission then we shouldn't add it to the list of notes for that SAC. 
I could reproduce the issue locally by desk-rejecting an assigned submission that doesn't have a meta review and try to remind the SAC with unsubmitted meta reviews.

PC console: check if the edge.head is pointing to an active submission

---

components/forum/Forum.js
hooks/useUser.js

this pr should remove useInterval call from forum page and use socket event instead
this pr should also revert changes of #2363 as it's not required anymore

Fix/ Forum - replace polling with event

---

components/webfield/RecruitmentForm.js
unitTests/RecruitmentForm.test.js

related to #2345 
invite assignment button has submission id and inviter id in query param and the value is now displayed
this pr should read the extra field values from param when available

Fix/ Recruitment Form - read extra fields value from query

---

components/group/WorkflowInvitations.js

this pr should instruction of workflow invitation in workflow timeline
if instruction is not available, use description as a fallback value
rational of this change is to avoid showing the text for users (description) to pc (instruction)

Fix/ Venu config - show instruction of workflow invitation

---

app/group/Group.module.scss
components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/Overview.js

Some pcs go to pc console just to access links at the bottom of the overview tab
this pr should split the data loading logic for timeline section so that it does not need to wait for all notes info

Fix/ PC Console - show timeline section before data loading is completed

---

components/webfield/ProgramChairConsole/Overview.js
lib/forum-utils.js

this is to fix a side effect caused by #2318 
which assume request form is in v2
this pr should pass apiVersion from request form so that it works for both v1 and v2 venue requests

Fix/ PC Console overview - read v1 request form content

---

components/webfield/ProgramChairConsole.js
components/webfield/ProgramChairConsole/Overview.js
lib/console-cache.js
package-lock.json
package.json
unitTests/console-cache.test.js

Summary of improvements:
- Reduce the size of `consoleData` object that is being stored in the browser db:
1. Remove `allProfiles` list, having `allProfilesMap` is enough
2. Keep a reduced version of the profile object: id, preferredName, title(extracted from current institution) and usernames
3. Keep the count of desk rejected and withdrawn notes instead of having the list of notes
4. Store the review list in the map only when it is not empty to avoid a large map with empty arrays. Same for metareviews, decisions, custom stages, etc
5. Keep a reduced version of each reply: id, forum, content, signatures. 
6. Remove `details.replies` from the note once the replies are being stored in each map(`officialReviewsByPaperNumberMap`, `metaReviewsByPaperNumberMap`, etc)
7. Precompute the …

PC Console: save a reduced version of the profile in console data

---

components/profile/RelationsSection.js

some old profiles have relations with no readers which will lead to error when user edit relations in profile edit
this pr should add a fallback value for relation readers

Fix/ Profile editor - handle relations with no readers

---

components/ErrorDisplay.js
components/webfield/AreaChairConsole.js
components/webfield/AuthorConsole.js
components/webfield/BidConsole.js
components/webfield/EthicsChairConsole.js
components/webfield/ProfileBidConsole.js
components/webfield/ProgramChairConsole.js
components/webfield/ReviewerConsole.js
components/webfield/SeniorAreaChairConsole.js
components/webfield/VenueHomepage.js

this pr should add a property 
withLayout
to ErrorDisplay component with default value set to true
this property controls whether to render <CommonLayout> in error display
it's correct for error display to render common layout for page level components
but it will be wrong for non-page level components such as consoles because group page already have layout

Fix/ ErrorDisplay in non-page component

---

components/EditorComponents/TextboxWidget.js

the code being removed was added in 
https://github.com/openreview/openreview-web/pull/1952/commits/6eb1b59fedccc4920db246ac8ada0c03f0130036#diff-84dd276a2477688d104491f2a2452446bf993556bccb816cad56f229e08ba43f
for json editor. exact purpose is not clear but implementation of json editor has been updated so i don't think it's necessary to keep it.
It's causing the textbox to update state too fast and break react rendering when user type fast enough in textbox.

Fix/ Textbox cursor jumping when typing fast
